[package]
name = "brainfuck"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }

[[bin]]
name = "bfrs"
path = "src/main.rs"

[[bin]]
name = "bff4-rs"
path = "src/bff4.rs"
