[package]
name = "brainfuck"
version = "1.1.1"
edition = "2021"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }

[profile.release]
panic = 'abort'

[[bin]]
name = "bfrs"
path = "src/main.rs"
