[package]
name = "brainfuck"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
wrapping_proc_macro = "1.0.0"

[profile.release]
codegen-units=1
lto="fat"

[[bin]]
name = "bfrs"
path = "src/main.rs"
